-- A link to one repair request, made for one garage that exists in the platform and shared with it (for example in WhatsApp).
-- The link opens a public page (no login) with a few details and the photos; see src/functions/viewSharedRequest.js.
--
-- Token: 32 random bytes as base64url (43 characters), generated by the API. It is the secret in the link, stored as is so that the
-- team can copy a link again later. A token only gives access to a limited view of one request, until it expires or is revoked.
--
-- Opens: "opened" means a person looked at the page. Chat apps and other link previewers fetch the page too (to build the preview);
-- those are counted separately (PreviewCount) and never as an open, so the open rate is not inflated by sharing the link itself.
CREATE TABLE dbo.RepairRequestShareLinks (
    Id              UNIQUEIDENTIFIER NOT NULL CONSTRAINT DF_ShareLinks_Id DEFAULT NEWSEQUENTIALID(),
    RepairRequestId UNIQUEIDENTIFIER NOT NULL,
    GarageId        UNIQUEIDENTIFIER NOT NULL,
    Token           CHAR(43)         NOT NULL,
    CreatedBy       VARCHAR(100)     NULL,
    CreatedAt       DATETIME2(0)     NOT NULL CONSTRAINT DF_ShareLinks_CreatedAt DEFAULT SYSUTCDATETIME(),
    ExpiresAt       DATETIME2(0)     NOT NULL,
    RevokedAt       DATETIME2(0)     NULL,
    FirstOpenedAt   DATETIME2(0)     NULL,
    LastOpenedAt    DATETIME2(0)     NULL,
    OpenCount       INT              NOT NULL CONSTRAINT DF_ShareLinks_OpenCount DEFAULT 0,
    FirstPreviewAt  DATETIME2(0)     NULL,
    PreviewCount    INT              NOT NULL CONSTRAINT DF_ShareLinks_PreviewCount DEFAULT 0,
    CONSTRAINT PK_ShareLinks PRIMARY KEY (Id),
    CONSTRAINT UQ_ShareLinks_Token UNIQUE (Token),
    CONSTRAINT FK_ShareLinks_RepairRequests FOREIGN KEY (RepairRequestId) REFERENCES dbo.RepairRequests (Id),
    CONSTRAINT FK_ShareLinks_Garages FOREIGN KEY (GarageId) REFERENCES dbo.Garages (Id),
    CONSTRAINT CK_ShareLinks_Expiry CHECK (ExpiresAt > CreatedAt)
);
GO

CREATE INDEX IX_ShareLinks_RepairRequestId ON dbo.RepairRequestShareLinks (RepairRequestId, GarageId);
GO

CREATE INDEX IX_ShareLinks_GarageId ON dbo.RepairRequestShareLinks (GarageId);
GO

CREATE INDEX IX_ShareLinks_CreatedAt ON dbo.RepairRequestShareLinks (CreatedAt DESC);
GO
